Repository hms-dbmi/PIC-SURE-Frontend, pull requests merged in 2024-07, with the labels that each got.

#80 [ALS-6241] Add variant explorer
  .env.example
  .env.test
  src/lib/components/ErrorAlert.svelte
  src/lib/components/datatable/Table.svelte
  src/lib/components/datatable/accessories/Rows.svelte
  src/lib/components/datatable/accessories/Search.svelte
  src/lib/components/datatable/accessories/Sort.svelte
  src/lib/components/explorer/results/ResultsPanel.svelte
  src/lib/configuration.ts
  src/lib/models/Variant.ts
  src/lib/models/query/Query.ts
  src/lib/stores/Filter.ts
  src/lib/stores/InfoColumns.ts
  src/lib/stores/Variants.ts
  src/routes/(picsure)/(public)/explorer/variant/+page.svelte
  tests/mock-data.ts
  tests/routes/explorer/genomic-filter/test.ts
  tests/routes/explorer/variant/test.ts
Labels: enhancement

#86 [ALS-6241] Update hasFilter
  src/lib/models/query/Query.ts
  src/routes/(picsure)/(public)/explorer/variant/+page.svelte
Labels: bug

#88 Don't save long term tokens
  src/lib/stores/User.ts
Labels: ignore-for-release

#87 [ALS-6771] Reorder header and change to login button
  src/app.postcss
  src/lib/components/Navigation.svelte
  src/lib/configuration.ts
Labels: enhancement

#89 [ALS-6093] Design updates for the landing page
  src/app.postcss
  src/lib/components/Stats.svelte
  src/lib/configuration.ts
  src/lib/stores/Stats.ts
  src/routes/(picsure)/(authorized)/analyze/+page.svelte
  src/routes/(picsure)/(authorized)/analyze/help/+page.svelte
  src/routes/(picsure)/(authorized)/analyze/start/+page.svelte
  src/routes/(picsure)/+page.svelte
  tests/routes/api/test.ts
  tests/routes/landing/test.ts
Labels: enhancement

#93 [ALS-6323] Design updates for results-panel
  src/app.postcss
  src/lib/components/explorer/results/ExportedVariable.svelte
  src/lib/components/explorer/results/ResultsPanel.svelte
  src/lib/components/explorer/results/SidePanel.svelte
  src/lib/configuration.ts
  src/lib/stores/Export.ts
  src/routes/(picsure)/(public)/explorer/+page.svelte
  src/routes/(picsure)/+layout.svelte
  tests/routes/explorer/test.ts
Labels: enhancement

#94 [ALS-6698] Design updates for genomic filter
  src/lib/components/HelpInfoPopup.svelte
  src/lib/components/explorer/gemone-filter/FilterSummary.svelte
  src/lib/components/explorer/gemone-filter/SNPSearch.svelte
  src/routes/(picsure)/(public)/explorer/genome-filter/+page.svelte
Labels: enhancement

#95 [ALS-6241] Design updates for variant explorer and datatables
  src/app.postcss
  src/lib/components/datatable/accessories/Pagination.svelte
  src/routes/(picsure)/(public)/explorer/variant/+page.svelte
Labels: enhancement

#97 [ALS-6855] Show clear all filters and exports link, even with 0 participants
  src/lib/components/explorer/results/ResultsPanel.svelte
  src/routes/(picsure)/(public)/explorer/variant/+page.svelte
  tests/routes/explorer/variant/test.ts
Labels: bug

#98 [CHORE] Add PIC-SURE favicon
  src/app.html
  static/favicon.ico
  static/favicon.png
  static/favicon.svg
Labels: enhancement

#102 [ALS-5477] Add terms modal and default text
  src/app.postcss
  src/lib/components/Footer.svelte
  src/lib/components/ModalWrapper.svelte
  src/lib/components/Stats.svelte
  src/lib/components/TermsModal.svelte
  src/lib/configuration.ts
  src/lib/models/Value.ts
  src/routes/(picsure)/+layout.svelte
  src/routes/+layout.svelte
  src/terms.svelte
Labels: enhancement

#103 [ALS-6878] Style Refinements
  postcss.config.cjs
  src/app.postcss
  src/lib/components/Content.svelte
  src/lib/components/Stats.svelte
  src/lib/components/UserToken.svelte
  src/lib/components/admin/authorization/cell/PrivilegeActions.svelte
  src/lib/components/admin/authorization/cell/RoleActions.svelte
  src/lib/components/admin/user/cell/Actions.svelte
  src/lib/components/buttons/AngleButton.svelte
  src/lib/components/buttons/CardButton.svelte
  src/lib/components/buttons/CopyButton.svelte
  src/lib/components/dataset/cell/Actions.svelte
  src/lib/components/dataset/cell/CopyButtonCell.svelte
  src/lib/components/datatable/Table.svelte
  src/lib/components/explorer/results/AddedFilter.svelte
  src/lib/components/explorer/results/ResultsPanel.svelte
  src/lib/configuration.ts
  src/routes/(authentication)/login/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/users/+page.svelte
  src/routes/(picsure)/(authorized)/analyze/+page.svelte
  src/routes/(picsure)/(authorized)/analyze/help/+page.svelte
  src/routes/(picsure)/(authorized)/analyze/start/+page.svelte
  src/routes/(picsure)/(authorized)/dataset/+page.svelte
  src/routes/(picsure)/(public)/explorer/genome-filter/+page.svelte
  src/routes/(picsure)/(public)/help/+page.svelte
  src/routes/(picsure)/+page.svelte
  tests/routes/dataset/test.ts
  tests/routes/landing/test.ts
  tests/routes/login/test.ts
Labels: enhancement

#104 [ALS-6892] CopyButton can use icon and has icon popup
  package-lock.json
  src/app.postcss
  src/lib/components/UserToken.svelte
  src/lib/components/buttons/CopyButton.svelte
  src/lib/components/dataset/cell/CopyButtonCell.svelte
  src/routes/(picsure)/(authorized)/dataset/+page.svelte
  tests/routes/api/test.ts
  tests/routes/dataset/test.ts
Labels: enhancement

#107 [ALS-0000] Update links and button colors for dark mode
  src/app.postcss
  src/lib/components/Footer.svelte
  src/lib/components/admin/authorization/cell/PrivilegeActions.svelte
  src/lib/components/admin/authorization/cell/RoleActions.svelte
  src/lib/components/admin/user/cell/Actions.svelte
  src/lib/components/dataset/cell/Actions.svelte
  src/lib/components/explorer/cell/Actions.svelte
  src/lib/components/explorer/results/AddedFilter.svelte
  src/lib/components/explorer/results/ExportedVariable.svelte
Labels: enhancement

#106 [ALS-6894] Update login page with dynamic width logo
  src/lib/components/Logo.svelte
  src/lib/components/Navigation.svelte
  src/lib/configuration.ts
  src/routes/(authentication)/login/+page.svelte
  tests/routes/login/test.ts
Labels: enhancement

#113 [Chore] Add reties to failed tests
  .github/workflows/tests.yml
  package.json
Labels: enhancement

#114 [ALS-6893] Remove stepper and add multiple snp filters feature
  src/app.postcss
  src/lib/components/buttons/AngleButton.svelte
  src/lib/components/buttons/CardButton.svelte
  src/lib/components/explorer/Panel.svelte
  src/lib/components/explorer/gemone-filter/FilterSummary.svelte
  src/lib/components/explorer/gemone-filter/FilterType.svelte
  src/lib/components/explorer/gemone-filter/SNPSearch.svelte
  src/lib/components/explorer/genome-filter/FilterType.svelte
  src/lib/components/explorer/genome-filter/GeneSearch.svelte
  src/lib/components/explorer/genome-filter/SNP/Edit.svelte
  src/lib/components/explorer/genome-filter/SNP/Search.svelte
  src/lib/components/explorer/genome-filter/SNP/Summary.svelte
  src/lib/components/explorer/genome-filter/SNPSearch.svelte
  src/lib/components/explorer/genome-filter/gene/Consequence.svelte
  src/lib/components/explorer/genome-filter/gene/Frequency.svelte
  src/lib/components/explorer/genome-filter/gene/Genes.svelte
  src/lib/components/explorer/genome-filter/gene/Summary.svelte
  src/lib/components/explorer/genome-filter/variant-data.json
  src/lib/components/explorer/results/AddedFilter.svelte
  src/lib/configuration.ts
  src/lib/models/Filter.ts
  src/lib/models/GenomeFilter.ts
  src/lib/models/InfoColumns.ts
  src/lib/models/query/Query.ts
  src/lib/stores/Filter.ts
  src/lib/stores/GeneFilter.ts
  src/lib/stores/GenomicFilter.ts
  src/lib/stores/InfoColumns.ts
  src/lib/stores/SNPFilter.ts
  src/routes/(picsure)/(public)/explorer/genome-filter/+page.svelte
  tests/mock-data.ts
  tests/routes/explorer/genomic-filter/gene-test.ts
  tests/routes/explorer/genomic-filter/snp-test.ts
  tests/routes/explorer/genomic-filter/test.ts
  tests/routes/explorer/variant/test.ts
Labels: enhancement

#116 [ALS-6938] Toggle light switch on footer right click
  src/lib/components/Footer.svelte
Labels: enhancement

#119 [ALS-6893] Remove warning on no SNP on search change and add padding to ANDs
  src/lib/components/explorer/genome-filter/SNP/Search.svelte
  src/lib/components/explorer/genome-filter/SNP/Summary.svelte
Labels: enhancement
