Repository hms-dbmi/PIC-SURE-Frontend, pull requests merged in 2024-11, with the labels that each got.

#284 [ALS-7776] Enforce gene req for genomic filters
  src/routes/(picsure)/(authorized)/explorer/genome-filter/+page.svelte
  tests/routes/explorer/genomic-filter/gene-test.ts
Labels: bug

#285 [ALS-7773] Handle 403 errors
  src/lib/api.ts
Labels: enhancement

#290 [CHORE] Fix facet filter test
  tests/routes/explorer/facets/test.ts
Labels: bug

#291 [ALS-7521] Make facet hiding work for categories with no hidden facets
  src/lib/components/explorer/FacetCategory.svelte
Labels: bug

#289 [ALS-6924] Take a Tour for PIC-SURE Demo
  .env.example
  .env.test
  src/lib/assets/TourConfiguration.json
  src/lib/assets/authTourConfiguration.json
  src/lib/assets/openTourConfiguration.json
  src/lib/components/tour/ExplorerTour.svelte
  src/lib/configuration.ts
  src/routes/(picsure)/(authorized)/explorer/+page.svelte
  src/routes/(picsure)/(public)/discover/+page.svelte
Labels: bug, enhancement

#296 [ALS-7696] Nested Facets
  src/lib/assets/dash.svg
  src/lib/components/explorer/FacetCategory.svelte
  src/lib/components/explorer/FacetItem.svelte
  src/lib/models/Search.ts
  src/lib/stores/Search.ts
  tests/mock-data.ts
  tests/routes/explorer/facets/test.ts
Labels: enhancement

#295 ALS-7712: ALlow PFB Export to 3rd party via signed URL
  src/lib/components/explorer/export/ExportStepper.svelte
  src/lib/configuration.ts
Labels: enhancement

#297 [ALS-7585] Add optional sample Ids checkbox
  .env.example
  .env.test
  src/lib/components/explorer/export/ExportStepper.svelte
  src/lib/configuration.ts
  src/lib/stores/Export.ts
Labels: enhancement

#301 [ALS-7813] Fix bug where user gets stuck when 401ed
  src/lib/components/explorer/Explorer.svelte
  src/lib/stores/Search.ts
  tests/mock-data.ts
  tests/routes/explorer/facets/test.ts
  tests/routes/explorer/test.ts
Labels: bug

#304 ALS-7849: Update terra hostname to bdc instance
  src/lib/components/explorer/export/ExportStepper.svelte
Labels: enhancement

#302 [ALS-6928] Add details drawer to dashboard
  .env.example
  .env.test
  src/lib/components/datatable/DashboardDrawer.svelte
  src/lib/components/datatable/DashboardLink.svelte
  src/lib/components/datatable/RemoteTable.svelte
  src/lib/components/datatable/Row.svelte
  src/lib/components/datatable/Table.svelte
  src/lib/configuration.ts
  src/lib/services/dictionary.ts
  src/routes/(picsure)/(authorized)/(admin)/admin/authorization/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/users/+page.svelte
  src/routes/(picsure)/(public)/dashboard/+page.svelte
  src/routes/(picsure)/+layout.svelte
  tests/mock-data.ts
  tests/routes/dashboard/test.ts
Labels: enhancement

#303 [ALS-7795] Tour on Discover does not apply a filter
  src/lib/assets/TourConfiguration.json
  src/lib/components/tour/ExplorerTour.svelte
  src/lib/configuration.ts
Labels: bug

#305 [ALS-7862] Update sort order of Dashboard
  src/lib/stores/Dashboard.ts
Labels: enhancement
