Repository hms-dbmi/PIC-SURE-Frontend, pull requests merged in 2024-06, with the labels that each got.

#64 [ALS-6345] Add Genomic Filter
  src/app.postcss
  src/lib/api.ts
  src/lib/components/Footer.svelte
  src/lib/components/HelpInfoPopup.svelte
  src/lib/components/Navigation.svelte
  src/lib/components/OptionsSelectionList.svelte
  src/lib/components/UserToken.svelte
  src/lib/components/buttons/AngleButton.svelte
  src/lib/components/buttons/CopyButton.svelte
  src/lib/components/dataset/cell/CopyButtonCell.svelte
  src/lib/components/explorer/AddFilter.svelte
  src/lib/components/explorer/Panel.svelte
  src/lib/components/explorer/cell/Actions.svelte
  src/lib/components/explorer/gemone-filter/FilterSummary.svelte
  src/lib/components/explorer/gemone-filter/FilterType.svelte
  src/lib/components/explorer/gemone-filter/SNPSearch.svelte
  src/lib/components/explorer/gemone-filter/SelectFrequency.svelte
  src/lib/components/explorer/gemone-filter/SelectGenes.svelte
  src/lib/components/explorer/gemone-filter/SelectedConsequence.svelte
  src/lib/components/explorer/gemone-filter/variant-data.json
  src/lib/components/explorer/results/AddedFilter.svelte
  src/lib/components/explorer/results/ResultsPanel.svelte
  src/lib/components/steppers/horizontal/Step.svelte
  src/lib/components/steppers/horizontal/Stepper.svelte
  src/lib/components/steppers/vertical/Step.svelte
  src/lib/configuration.ts
  src/lib/models/Filter.ts
  src/lib/models/GemoneFilter.ts
  src/lib/models/InfoColumns.ts
  src/lib/models/query/Query.ts
  src/lib/stores/GenomicFilter.ts
  src/lib/stores/InfoColumns.ts
  src/lib/types.ts
  src/lib/utilities/Validation.ts
  src/routes/(authentication)/login/+layout.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/requests/+page.svelte
  src/routes/(picsure)/(authorized)/api/help/+page.svelte
  src/routes/(picsure)/(authorized)/api/start/+page.svelte
  src/routes/(picsure)/(public)/explorer/+page.svelte
  src/routes/(picsure)/(public)/explorer/genome-filter/+page.svelte
  tests/mock-data.ts
  tests/routes/explorer/genomic-filter/test.ts
  tests/routes/explorer/test.ts
Labels: enhancement

#65 [ALS-6345] Update genomic filter edit buttons in result panel
  src/lib/components/explorer/gemone-filter/FilterType.svelte
  src/lib/components/explorer/results/AddedFilter.svelte
  src/lib/components/steppers/horizontal/Stepper.svelte
  src/lib/models/GemoneFilter.ts
  src/lib/stores/GenomicFilter.ts
  src/routes/(picsure)/(public)/explorer/genome-filter/+page.svelte
  tests/routes/explorer/genomic-filter/test.ts
Labels: enhancement

#66 [ALS-6146] [ALS-6325] Authorization and User management page updates.
  src/lib/components/Content.svelte
  src/lib/components/admin/authorization/cell/PrivilegeActions.svelte
  src/lib/components/admin/authorization/cell/RoleActions.svelte
  src/lib/components/admin/user/cell/Actions.svelte
  src/lib/components/buttons/AngleButton.svelte
  src/lib/components/buttons/CopyButton.svelte
  src/lib/components/dataset/cell/Actions.svelte
  src/lib/components/datatable/Row.svelte
  src/lib/components/datatable/Table.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/authorization/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/authorization/privilege/[uuid]/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/authorization/privilege/[uuid]/edit/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/authorization/privilege/new/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/authorization/role/[uuid]/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/authorization/role/[uuid]/edit/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/authorization/role/new/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/users/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/users/[uuid]/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/users/[uuid]/edit/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/users/new/+page.svelte
  src/routes/(picsure)/(authorized)/dataset/+page.svelte
  src/routes/(picsure)/(authorized)/dataset/[uuid]/+page.svelte
  src/routes/(picsure)/(public)/explorer/genome-filter/+page.svelte
  tests/routes/admin/authorization/test.ts
  tests/routes/admin/users/test.ts
  tests/routes/dataset/test.ts
Labels: enhancement

#67 [ALS-6270] Shrink header navigation and links
  src/app.postcss
  src/lib/components/Navigation.svelte
  src/routes/(authentication)/login/+layout.svelte
Labels: enhancement

#69 [ALS-6648] Update ExpandableRow store and components...
  src/lib/components/datatable/Row.svelte
  src/lib/components/datatable/Table.svelte
  src/lib/components/explorer/AddFilter.svelte
  src/lib/components/explorer/cell/Actions.svelte
  src/lib/stores/ExpandableRow.ts
  src/routes/(picsure)/(authorized)/(admin)/admin/authorization/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/users/+page.svelte
  src/routes/(picsure)/(authorized)/dataset/+page.svelte
  src/routes/(picsure)/(public)/explorer/+page.svelte
Labels: enhancement

#70 [ALS-6647] Change export variable to update when row data changes
  src/lib/components/explorer/cell/Actions.svelte
Labels: bug

#72 [ALS-6698] Update copy and fix small bugs
  src/lib/components/Content.svelte
  src/lib/components/HelpInfoPopup.svelte
  src/lib/components/OptionsSelectionList.svelte
  src/lib/components/buttons/AngleButton.svelte
  src/lib/components/explorer/Panel.svelte
  src/lib/components/explorer/gemone-filter/FilterSummary.svelte
  src/lib/components/explorer/gemone-filter/FilterType.svelte
  src/lib/components/explorer/gemone-filter/SNPSearch.svelte
  src/lib/components/explorer/gemone-filter/SelectGenes.svelte
  src/lib/components/explorer/results/AddedFilter.svelte
  src/lib/components/steppers/horizontal/Step.svelte
  src/lib/components/steppers/horizontal/Stepper.svelte
  src/lib/models/Filter.ts
  src/lib/stores/InfoColumns.ts
  src/routes/(picsure)/(public)/explorer/genome-filter/+page.svelte
  tests/routes/explorer/genomic-filter/test.ts
Labels: bug, enhancement

#62 [ALS-6655 & ALS-6699] Login, Themes, & Dynamic authentication providers
  .env.example
  .env.test
  Dockerfile
  pic-sure-theme.ts
  pic-sure-themes.ts
  playwright.config.ts
  src/app.html
  src/app.postcss
  src/hooks.client.ts
  src/hooks.server.ts
  src/lib/AuthProviderRegistry.ts
  src/lib/assets/dots.svg
  src/lib/auth/AUTH0.ts
  src/lib/auth/FENCE.ts
  src/lib/auth/RAS.ts
  src/lib/components/Dots.svelte
  src/lib/components/Footer.svelte
  src/lib/components/LoginButton.svelte
  src/lib/components/Logo.svelte
  src/lib/components/Navigation.svelte
  src/lib/components/buttons/AngleButton.svelte
  src/lib/configuration.ts
  src/lib/models/AuthProvider.ts
  src/lib/models/Filter.ts
  src/lib/stores/User.ts
  src/routes/(authentication)/login/+layout.svelte
  src/routes/(authentication)/login/+page.server.ts
  src/routes/(authentication)/login/+page.svelte
  src/routes/(authentication)/login/error/+error.svelte
  src/routes/(authentication)/login/error/+page.svelte
  src/routes/(authentication)/login/loading/+page.server.ts
  src/routes/(authentication)/login/loading/+page.svelte
  src/routes/(picsure)/(public)/help/+page.svelte
  static/app-logo.png
  static/bdc-logo.svg
  static/gic-logo.svg
  supervisord.conf
  tailwind.config.ts
  tests/lib/component/navigation/test.ts
  tests/mock-data.ts
  tests/routes/login/test.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#77 [npm][docker] Dependabot version updates
  Dockerfile
  Dockerfile.node
  package-lock.json
  package.json
Labels: dependencies

#79 [CHORE] Add docker build workflow
  .github/workflows/check-docker.yml
  README.md
Labels: enhancement

#78 [ALS-0000] Fix bugs in session token lifecycle
  src/lib/api.ts
  src/lib/components/UserToken.svelte
  src/lib/stores/User.ts
  src/routes/(picsure)/(authorized)/+layout.ts
  tests/custom-context.ts
  tests/mock-data.ts
  tests/routes/api/test.ts
Labels: bug

#81 [ALS-6667] Footer changes
  src/lib/components/Footer.svelte
  src/lib/configuration.ts
Labels: enhancement
