Repository hms-dbmi/PIC-SURE-Frontend, pull requests merged in 2024-10, with the labels that each got.

#220 George UI fixes
  .env.test
  Dockerfile.bdc
  src/lib/assets/authTourConfiguration.json
  src/lib/assets/openTourConfiguration.json
  src/lib/components/Stats.svelte
  src/lib/components/explorer/FacetCategory.svelte
  src/lib/components/tour/ExplorerTour.svelte
  src/lib/components/tour/TourModal.svelte
  src/routes/(authentication)/login/+page.svelte
  static/bdc-favicon.png
  static/bdc-logo.svg
  tests/routes/login/test.ts
Labels: bug, enhancement

#212 Disable directory listing in Httpd
  Dockerfile
  Dockerfile.bdc
Labels: enhancement

#224 Lazy load Plotly only in browser environments
  src/lib/components/explorer/Visualizations.svelte
Labels: bug

#222 [ALS-7441] Hide facets that are always 0
  src/lib/components/explorer/FacetCategory.svelte
  src/lib/services/dictionary.ts
Labels: enhancement

#219 [ALS-6734] BDC Dashboard changes
  src/lib/components/datatable/DashboardLink.svelte
  src/lib/components/datatable/Link.svelte
  src/lib/components/datatable/Table.svelte
  src/lib/stores/Dashboard.ts
  src/routes/(picsure)/(public)/dashboard/+page.svelte
Labels: enhancement

#227 [CHORE] Move explorer pages
  src/routes/(picsure)/(authorized)/explorer/+page.svelte
  src/routes/(picsure)/(authorized)/explorer/distributions/+page.svelte
  src/routes/(picsure)/(authorized)/explorer/export/+page.svelte
  src/routes/(picsure)/(authorized)/explorer/genome-filter/+page.svelte
  src/routes/(picsure)/(authorized)/explorer/variant/+page.svelte
Labels: ignore-for-release

#231 ALS-7504: Fix export tabgroup
  src/lib/components/explorer/export/ExportStepper.svelte
Labels: bug

#232 [CHORE] Fix queryTemplate
  src/lib/QueryBuilder.ts
Labels: bug

#228 [ALS-7489] Add hyperlinks to analysis workspace examples
  src/routes/(picsure)/(authorized)/analyze/+page.svelte
Labels: enhancement

#234 [ALS-7512] Hide Pagination and Search on Dashboard
  src/lib/components/datatable/Table.svelte
  src/routes/(picsure)/(public)/dashboard/+page.svelte
Labels: ignore-for-release

#233 [ALS-7357] Check filters on navigation
  src/lib/components/FilterWarning.svelte
  src/lib/components/explorer/results/SidePanel.svelte
  src/lib/models/Filter.ts
  src/lib/stores/Filter.ts
  src/lib/stores/SidePanel.ts
  src/routes/(authentication)/login/loading/+page.svelte
  src/routes/(picsure)/(authorized)/+layout.ts
  src/routes/(picsure)/(public)/discover/+page.svelte
  src/routes/(picsure)/+layout.svelte
  tests/mock-data.ts
  tests/routes/explorer/genomic-filter/gene-test.ts
  tests/routes/explorer/genomic-filter/snp-test.ts
  tests/routes/explorer/variant/test.ts
Labels: enhancement

#235 [ALS-7484] Redirect on 404s and blank screen on login errors
  src/routes/(authentication)/login/loading/+page.svelte
  src/routes/+layout.ts
Labels: enhancement

#239 Bump micromatch
  package-lock.json
Labels: enhancement, dependencies

#240 [ALS-7491] Hide i icon for dataset view
  src/lib/components/dataset/cell/Actions.svelte
  tests/routes/dataset/test.ts
Labels: ignore-for-release

#241 Enhance Google Analytics and Consent Tracking
  .env.example
  .env.test
  src/lib/components/tracking/GoogleAnalytics.svelte
  src/lib/components/tracking/GoogleConsents.svelte
Labels: bug, enhancement

#242 [ALS-7492] Fix loading more values on the add filter page.
  src/lib/components/OptionsSelectionList.svelte
  src/lib/components/explorer/AddFilter.svelte
  src/lib/components/explorer/genome-filter/gene/Genes.svelte
  tests/lib/component/optional-selection-list/test.ts
  tests/mock-data.ts
Labels: bug

#245 Update login button appearance and add support for dynamic images
  src/lib/assets/login/NIH_2013_logo_vertical_text_removed.svg
  src/lib/components/LoginButton.svelte
  src/lib/models/AuthProvider.ts
  src/routes/(authentication)/login/+page.svelte
  static/NIH_2013_logo_vertical_text_removed.svg
Labels: enhancement

#246 Update branch names
  .github/workflows/tests.yml
Labels: ignore-for-release

#250 [ALS-7586] Update disabled color
  src/app.postcss
Labels: enhancement

#251 [ALS-7521] Make facet hiding work for categories with no hidden facets
  src/lib/components/explorer/FacetCategory.svelte
Labels: bug

#262 [ALS-6967] Updates for all in one integration
  Dockerfile
  Dockerfile.prod
  vite.config.ts
Labels: ignore-for-release

#252 [ALS-7501] Refactor and fix tool suite conditions
  src/lib/components/explorer/results/ResultsPanel.svelte
Labels: bug

#269 [ALS-7658] Add json file for code blocks
  src/lib/assets/codeBlocks.json
  src/lib/components/explorer/export/ExportStepper.svelte
  src/routes/(picsure)/(authorized)/analyze/+page.svelte
Labels: enhancement

#229 Enhance GA tracking consent check
  src/lib/components/tracking/GoogleAnalytics.svelte
  src/lib/components/tracking/GoogleConsents.svelte
  src/lib/components/tracking/GoogleTagManger.svelte
  src/lib/components/tracking/GoogleTracking.svelte
  src/routes/+layout.svelte
  tests/routes/login/test.ts
Labels: bug

#263 [ALS-7506][ALS-7646] Fix logout bug & add message when timed out
  src/lib/api.ts
  src/lib/components/Navigation.svelte
  src/lib/services/dictionary.ts
  src/lib/stores/User.ts
  src/routes/(authentication)/login/+layout.svelte
  src/routes/(authentication)/login/+page.svelte
Labels: bug

#271 [ALS-7605] Add a confirm modal to downloads
  src/lib/assets/configuration.json
  src/lib/components/Footer.svelte
  src/lib/components/explorer/export/ExportStepper.svelte
  src/lib/components/modals/Confirmation.svelte
  src/lib/components/modals/FilterWarning.svelte
  src/lib/components/modals/ModalWrapper.svelte
  src/lib/components/modals/TermsModal.svelte
  src/lib/configuration.ts
  src/lib/types.ts
  src/routes/(picsure)/+layout.svelte
Labels: enhancement

#270 [ALS-7494] Ensure selected facet counts are updated when required
  src/lib/components/explorer/FacetCategory.svelte
Labels: bug

#272 [ALS-7612] Update BDC surface color
  pic-sure-themes.ts
Labels: enhancement

#273 Handle better AuthProvider logout
  src/lib/stores/User.ts
  src/routes/(picsure)/+layout.ts
Labels: bug

#279 [ALS-7658] Make dataset id dynamic in R
  src/lib/assets/codeBlocks.json
  src/lib/components/explorer/export/ExportStepper.svelte
Labels: enhancement
