Repository hms-dbmi/PIC-SURE-Frontend, pull requests merged in 2024-09, with the labels that each got.

#156 [ALS-7187] Results panel UI tweaks
  src/app.postcss
  src/lib/components/explorer/export/ExportStepper.svelte
  src/lib/components/explorer/genome-filter/FilterType.svelte
  src/lib/components/explorer/genome-filter/gene/Consequence.svelte
  src/lib/components/explorer/results/AddedFilter.svelte
  src/lib/components/explorer/results/ExportedVariable.svelte
  src/lib/components/explorer/results/ResultsPanel.svelte
  src/routes/(picsure)/(authorized)/analyze/example/+page.svelte
  src/routes/(picsure)/(public)/explorer/distributions/+page.svelte
  src/routes/(picsure)/(public)/explorer/variant/+page.svelte
  src/routes/(picsure)/+page.svelte
Labels: enhancement

#158 [CHORE] Add local dev docker options
  Dockerfile.dev
  Dockerfile.local
  Dockerfile.node
  Dockerfile.prod
  supervisord-dev.conf
  supervisord-local.conf
Labels: enhancement, docker

#162 [FIX] Add ids for tour
  src/lib/components/explorer/AddFilter.svelte
  src/lib/components/tour/ExplorerTour.svelte
  tests/mock-data.ts
  tests/routes/explorer/tour/test.ts
Labels: bug

#163 [CHORE] Change query to Dataset
  src/routes/(picsure)/(authorized)/dataset/+page.svelte
Labels: enhancement

#155 [ALS-7040] Externalize branding config
  src/lib/assets/configuration.json
  src/lib/components/Footer.svelte
  src/lib/components/Stats.svelte
  src/lib/components/explorer/genome-filter/GeneSearch.svelte
  src/lib/components/explorer/results/ResultsPanel.svelte
  src/lib/components/tour/ExplorerTour.svelte
  src/lib/configuration.ts
  src/lib/types.ts
  src/routes/(authentication)/login/+page.svelte
  src/routes/(picsure)/(public)/help/+page.svelte
  src/routes/(picsure)/+page.svelte
  src/routes/+layout.svelte
  tests/routes/api/test.ts
  tests/routes/explorer/genomic-filter/gene-test.ts
  tests/routes/help/test.ts
  tests/routes/landing/test.ts
  tests/routes/login/test.ts
Labels: enhancement

#168 [ALS-7263] Add QueryTemplate Support
  src/lib/QueryBuilder.ts
  src/lib/components/UserToken.svelte
  src/lib/components/explorer/AddFilter.svelte
  src/lib/components/explorer/export/Summary.svelte
  src/lib/components/explorer/results/ResultsPanel.svelte
  src/lib/components/explorer/results/SidePanel.svelte
  src/lib/components/tour/TourModal.svelte
  src/lib/configuration.ts
  src/lib/models/User.ts
  src/lib/models/api/Request.ts
  src/lib/models/query/Query.ts
  src/lib/stores/Filter.ts
  src/lib/stores/User.ts
  src/routes/(picsure)/(public)/explorer/distributions/+page.svelte
  src/routes/(picsure)/(public)/explorer/export/+page.svelte
  src/routes/(picsure)/(public)/explorer/variant/+page.svelte
  tests/custom-context.ts
  tests/mock-data.ts
Labels: enhancement

#178 [ALS-7179] Dashboard UI
  .env.example
  .gitignore
  src/lib/components/datatable/Link.svelte
  src/lib/configuration.ts
  src/lib/stores/Dashboard.ts
  src/routes/(picsure)/(public)/dashboard/+page.svelte
  tests/mock-data.ts
  tests/routes/dashboard/test.ts
Labels: enhancement

#180 ALS-7000: BDC changes for data export
  .gitignore
  src/lib/components/explorer/export/ExportStepper.svelte
  src/lib/components/explorer/export/Summary.svelte
  src/lib/models/query/Query.ts
  src/routes/(picsure)/(public)/explorer/export/+page.svelte
Labels: enhancement

#181 [ALS-7323] Update BDC theme
  Dockerfile.bdc
  pic-sure-themes.ts
Labels: enhancement

#183 Fix logout loop
  src/lib/stores/User.ts
Labels: bug

#182 [ALS-7179] - Revisions, pull link anchor directly
  src/lib/configuration.ts
  src/lib/types.ts
  src/routes/(picsure)/(public)/dashboard/+page.svelte
  tests/mock-data.ts
Labels: bug

#185 ALS-7300: Prepare for Analysis Page in BDC
  src/lib/assets/configuration.json
  src/lib/configuration.ts
  src/routes/(picsure)/(authorized)/analyze/+page.svelte
  src/routes/(picsure)/(authorized)/analyze/example/+page.svelte
Labels: enhancement

#184 [ALS-6705] Update discover results
  src/app.postcss
  src/lib/QueryBuilder.ts
  src/lib/assets/configuration.json
  src/lib/components/explorer/results/ResultsPanel.svelte
  src/lib/configuration.ts
  src/lib/models/query/Query.ts
  src/lib/services/hpds.ts
  tests/mock-data.ts
  tests/routes/discover/test.ts
  tests/routes/explorer/test.ts
Labels: enhancement

#186 [ALS-6937] Update Landing page stats
  src/lib/components/Stats.svelte
  src/lib/services/dictionary.ts
  src/lib/stores/Stats.ts
Labels: enhancement

#187 [BUG] Remove token for open access requests
  src/lib/components/explorer/Visualizations.svelte
Labels: bug

#194 Fix summary font
  src/lib/components/explorer/export/Summary.svelte
Labels: bug

#189 [ALS-6747][ALS-6926] Make tour configurable
  src/lib/assets/authTourConfiguration.json
  src/lib/assets/openTourConfiguration.json
  src/lib/assets/testConfiguration.json
  src/lib/components/explorer/Explorer.svelte
  src/lib/components/tour/ExplorerTour.svelte
  src/lib/components/tour/TourModal.svelte
  src/routes/(picsure)/(public)/discover/+page.svelte
  src/routes/(picsure)/(public)/explorer/+page.svelte
  supervisord-local.conf
Labels: enhancement

#201 [ALS-7371], [ALS-7363] Overflow elipses, variable name, description in edit modal
  src/lib/components/explorer/AddFilter.svelte
  src/lib/components/explorer/results/AddedFilter.svelte
Labels: bug

#195 [ALS-7054] Add more info to the search results
  src/lib/components/explorer/ResultInfoComponent.svelte
  src/lib/models/Search.ts
Labels: enhancement

#188 [ALS-6937] Support open access users for actions
  src/lib/assets/configuration.json
  src/lib/components/Stats.svelte
  src/lib/stores/Stats.ts
  src/lib/types.ts
  src/routes/(picsure)/+page.svelte
  tests/mock-data.ts
  tests/routes/api/test.ts
  tests/routes/explorer/genomic-filter/gene-test.ts
  tests/routes/help/test.ts
  tests/routes/landing/test.ts
  tests/routes/login/test.ts
Labels: enhancement

#202 [ALS-7400] Add support for additional columns
  src/lib/assets/authTourConfiguration.json
  src/lib/assets/configuration.json
  src/lib/assets/openTourConfiguration.json
  src/lib/assets/testConfiguration.json
  src/lib/components/explorer/Explorer.svelte
  src/lib/components/tour/ExplorerTour.svelte
  src/lib/types.ts
  tests/routes/explorer/results-panel/test.ts
Labels: enhancement

#204 [ALS-7402] Allow both types of genomic filters to toggle off
  .env.example
  .env.test
  .eslintignore
  src/lib/components/explorer/Explorer.svelte
  src/lib/components/explorer/genome-filter/FilterType.svelte
  src/lib/configuration.ts
Labels: enhancement

#203 ALS-6735: Transition from explore to discover page
  src/lib/components/explorer/export/ExportStepper.svelte
  src/lib/components/explorer/results/ResultsPanel.svelte
  src/lib/models/Filter.ts
  src/lib/models/Search.ts
  src/lib/services/datasets.ts
  src/lib/stores/Filter.ts
  src/routes/(picsure)/(public)/discover/+page.svelte
  src/routes/(picsure)/(public)/explorer/+page.svelte
  src/routes/(picsure)/(public)/explorer/export/+page.svelte
  tests/routes/explorer/test.ts
Labels: enhancement

#206 [BUG] Fix bugs in results panel in BDC
  src/lib/components/explorer/results/ResultsPanel.svelte
  src/lib/stores/User.ts
  src/routes/(picsure)/(public)/dashboard/+page.svelte
Labels: bug

#208 Disable filters on discover if allowFiltering is false
  src/app.postcss
  src/lib/components/datatable/Row.svelte
  src/lib/components/explorer/Explorer.svelte
  src/lib/components/explorer/cell/Actions.svelte
  src/lib/configuration.ts
  tests/mock-data.ts
  tests/routes/discover/test.ts
Labels: enhancement

#209 Update discover warning
  src/routes/(picsure)/(public)/discover/+page.svelte
Labels: enhancement

#210 Fix bug and make tour more stable
  src/lib/assets/authTourConfiguration.json
  src/lib/assets/openTourConfiguration.json
  src/lib/assets/testConfiguration.json
  src/lib/components/tour/ExplorerTour.svelte
Labels: bug

#211 [FIX] Use correct data on Info Screen
  src/lib/components/explorer/ResultInfoComponent.svelte
  tests/mock-data.ts
  tests/routes/explorer/test.ts
Labels: bug

#207 ALS-7357: Store filters from discover page when user logs in
  src/lib/stores/Filter.ts
  src/routes/(authentication)/login/loading/+page.svelte
  src/routes/(picsure)/(public)/explorer/+page.svelte
Labels: enhancement
