Repository hms-dbmi/PIC-SURE-Frontend, pull requests merged in 2025-05, with the labels that each got.

#418 [ALS-8936] Add tests for Export page
  src/lib/components/explorer/export/ExportStepper.svelte
  tests/mock-data.ts
  tests/routes/explorer/export/test.ts
Labels: enhancement

#417 [ALS-8951] Fix bug where the "Show More" facets button was incorrectly shown
  src/lib/components/explorer/FacetCategory.svelte
  src/lib/stores/Dictionary.ts
  tests/mock-data.ts
  tests/routes/explorer/facets/test.ts
Labels: bug

#419 [ALS-8694] Fix [Object Object] Bug
  src/lib/components/explorer/results/ResultsPanel.svelte
Labels: bug

#420 [Bug] Add redirect to admin pages
  src/routes/(picsure)/(authorized)/(admin)/admin/+layout.ts
  tests/routes/admin/requests/test.ts
Labels: bug

#423 [ALS-9010] Dynamically update code block PIC-SURE urls
  src/lib/assets/configuration.json
  src/lib/auth/AUTH0.ts
  src/lib/configuration.ts
Labels: enhancement

#422 [ALS-8881] Handle conflict error status
  src/lib/components/admin/configuration/cell/ConnectionActions.svelte
  src/lib/components/admin/configuration/cell/PrivilegeActions.svelte
  src/lib/components/admin/configuration/cell/RoleActions.svelte
Labels: bug

#421 [ALS-8970] Fix SNP search and handle errors
  src/lib/components/explorer/genome-filter/SNP/Search.svelte
  src/lib/stores/SNPFilter.ts
  vite.config.ts
Labels: bug

#425 [ALS-9023] Update SNP language & bug fix
  src/lib/components/explorer/genome-filter/FilterType.svelte
  src/lib/components/explorer/genome-filter/SNP/Search.svelte
  src/lib/components/explorer/genome-filter/SNPSearch.svelte
  src/lib/stores/SNPFilter.ts
Labels: bug

#426 Configuration pages handle Admins
  src/lib/components/admin/configuration/ConnectionForm.svelte
  src/lib/components/admin/configuration/PrivilegeForm.svelte
  src/lib/components/admin/configuration/RequiredFieldsList.svelte
  src/lib/components/admin/configuration/RoleForm.svelte
  src/lib/components/admin/configuration/cell/ConnectionActions.svelte
  src/lib/components/admin/configuration/cell/PrivilegeActions.svelte
  src/lib/components/admin/configuration/cell/RoleActions.svelte
  src/lib/configuration.ts
  src/lib/stores/User.ts
  src/routes/(picsure)/(authorized)/(admin)/admin/+layout.ts
  src/routes/(picsure)/(authorized)/(admin)/admin/configuration/+page.svelte
  tests/routes/admin/configuration/connections/test.ts
  tests/routes/admin/configuration/privileges/test.ts
  tests/routes/admin/configuration/roles/test.ts
Labels: bug

#427 [BUG] Exports without display fallback to name
  src/lib/components/explorer/results/ExportedVariable.svelte
  src/routes/(picsure)/(authorized)/explorer/export/+page.svelte
Labels: bug

#429 Fix 500 error when landing on page
  src/lib/stores/User.ts
Labels: bug

#435 [CHORE] Delete .github/workflows/sync-release.yml
  .github/workflows/sync-release.yml
Labels: ignore-for-release

#430 [ALS-7717] BDC faults and fixes
  .env.example
  Dockerfile.bdc
  src/lib/api.ts
  src/lib/components/Footer.svelte
  src/lib/components/Logo.svelte
  src/lib/components/Navigation.svelte
  src/lib/components/explorer/FilterWarning.svelte
  src/lib/components/explorer/export/ExportStepper.svelte
  src/routes/(authentication)/login/+page.svelte
  src/routes/(picsure)/+layout.svelte
  src/styles/app.css
  src/styles/theme.css
  vite.config.ts
Labels: enhancement

#439 Add request deduplication using request ID checks to prevent race con…
  src/lib/components/explorer/results/ResultsPanel.svelte
Labels: bug

#437 [ALS-8965] Add anti Clickjacking frame-breaker
  src/app.html
Labels: enhancement

#447 [CHROE] Fix merge conflict
  src/lib/components/explorer/HierarchyComponent.svelte
Labels: bug
