Repository hms-dbmi/PIC-SURE-Frontend, pull requests merged in 2025-01, with the labels that each got.

#336 [ALS-7709] Dynamically update navigation based on logged in status
  src/lib/components/HelpInfoPopup.svelte
  src/lib/components/Navigation.svelte
  src/lib/components/admin/user/cell/Actions.svelte
  src/lib/components/buttons/CardButton.svelte
  src/lib/components/buttons/CopyButton.svelte
  src/lib/components/dataset/cell/Actions.svelte
  src/lib/components/datatable/RemoteTable.svelte
  src/lib/components/datatable/Table.svelte
  src/lib/components/explorer/AddFilter.svelte
  src/lib/components/explorer/FacetCategory.svelte
  src/lib/components/explorer/FacetItem.svelte
  src/lib/components/explorer/genome-filter/SNP/Summary.svelte
  src/lib/components/explorer/results/ExportedVariable.svelte
  src/lib/components/request/modals/DataSummary.svelte
  src/lib/stores/User.ts
  src/routes/(picsure)/(authorized)/(admin)/admin/authorization/privilege/[uuid]/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/authorization/role/[uuid]/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/requests/+page.svelte
  src/routes/(picsure)/(authorized)/(admin)/admin/users/[uuid]/+page.svelte
  src/routes/(picsure)/(authorized)/dataset/[uuid]/+page.svelte
  src/routes/(picsure)/+page.svelte
Labels: enhancement

#340 [ALS-8139] Make sure facets have their references
  src/lib/components/explorer/FacetCategory.svelte
  src/lib/components/explorer/FacetItem.svelte
  src/lib/services/dictionary.ts
Labels: enhancement

#343 [CHORE] Update dependancies
  package-lock.json
  package.json
Labels: dependencies

#352 Update local Docker and supervisord to run mounted src folder with dev logging
  Dockerfile.local
  supervisord-local.conf
Labels: enhancement

#353 [ALS-7423] Enhance ProgressRadial alignment in FacetSideBar
  src/lib/components/explorer/FacetSideBar.svelte
Labels: bug

#354 Update vite.config.ts file to add allowed hosts.
  package-lock.json
  package.json
  vite.config.ts
Labels: enhancement

#344 [ALS-7674] Remove Facet Reset
  src/lib/components/Searchbox.svelte
  src/lib/components/explorer/Explorer.svelte
  tests/routes/explorer/test.ts
Labels: enhancement

#356 [ALS-7841] Allow unchecking of facet when count is 0
  .gitignore
  src/lib/components/explorer/FacetItem.svelte
  tests/routes/explorer/facets/test.ts
Labels: enhancement

#358 ALS-8239: Fix PFB encoding issues
  src/lib/api.ts
Labels: bug

#357 [ALS-532] Move TOS flag from branding to env variables
  src/lib/assets/configuration.json
  src/lib/components/Footer.svelte
  src/lib/configuration.ts
  src/lib/types.ts
Labels: enhancement

#359 [ALS-7317] Add configuration for analysis page instructions
  src/lib/assets/configuration.json
  src/lib/configuration.ts
  src/lib/types.ts
  src/routes/(picsure)/(authorized)/analyze/+page.svelte
Labels: enhancement
