Repository hms-dbmi/PIC-SURE-Frontend, pull requests merged in 2025-08, with the labels that each got.

#504 [CHORE] Update GIC theme
  src/styles/app.css
  src/styles/theme.css
Labels: ignore-for-release

#496 [ALS-6890] Finalize Data Request page
  src/lib/assets/configuration.json
  src/lib/components/HelpInfoPopup.svelte
  src/lib/components/Popover.svelte
  src/lib/components/explorer/genome-filter/GeneSearch.svelte
  src/lib/components/explorer/genome-filter/SNPSearch.svelte
  src/lib/components/landing/Stat.svelte
  src/lib/components/request/Grid.svelte
  src/lib/components/request/GridCell.svelte
  src/lib/components/request/StatusIndicator.svelte
  src/lib/components/request/modals/DataSummary.svelte
  src/lib/components/request/modals/SendDataModal.svelte
  src/lib/components/steppers/vertical/Step.svelte
  src/lib/configuration.ts
  src/lib/models/DataRequest.ts
  src/lib/services/datarequest.ts
  src/lib/stores/DataRequest.ts
  src/lib/types.ts
  src/routes/(picsure)/(authorized)/(admin)/admin/requests/+page.svelte
  src/routes/(picsure)/(authorized)/dataset/request/+page.svelte
  tests/mock-data.ts
  tests/routes/dataset/requests/test.ts
Labels: enhancement

#506 [CHORE] Bug Fixes
  src/lib/components/HelpInfoPopup.svelte
  src/lib/components/Popover.svelte
  src/lib/components/admin/configuration/PrivilegeForm.svelte
  src/lib/components/admin/user/UserForm.svelte
  src/lib/components/datatable/accessories/Rows.svelte
  src/lib/components/explorer/FilterWarning.svelte
  src/lib/components/explorer/genome-filter/SNP/Edit.svelte
  src/lib/components/request/StatusIndicator.svelte
  src/lib/configuration.ts
  src/routes/(authentication)/login/+page.svelte
  src/routes/(picsure)/(authorized)/dataset/request/+page.svelte
  src/styles/app.css
Labels: ignore-for-release

#516 [ALS-9675] Move Cohort key to top of page
  src/routes/(picsure)/(authorized)/explorer/cohort/+page.svelte
Labels: enhancement

#514 Wrap table handler subscribers in initialization method
  src/lib/components/explorer/Explorer.svelte
  src/lib/stores/Search.ts
Labels: enhancement

#520 [ALS-9687] Do not repeat toasts
  src/lib/stores/ResultStore.ts
  src/lib/stores/Stats.ts
  src/lib/toaster.ts
  src/routes/(picsure)/(authorized)/explorer/variant/+page.svelte
  tests/routes/explorer/results-panel/test.ts
Labels: bug

#522 [ALS-9549] Move login redirect
  src/lib/components/Shell.svelte
  src/routes/(picsure)/+layout.ts
  src/routes/+layout.server.ts
  src/routes/+layout.ts
Labels: bug
