Repository hms-dbmi/PIC-SURE-Frontend, pull requests merged in 2025-07, with the labels that each got.

#476 [ALS-8136] Add Cohort Details page
  .env.test
  src/lib/assets/configuration.json
  src/lib/components/explorer/Visualizations.svelte
  src/lib/components/explorer/export/ExportStepper.svelte
  src/lib/components/explorer/genome-filter/gene/Genes.svelte
  src/lib/components/explorer/results/Counts.svelte
  src/lib/components/explorer/results/ResultsPanel.svelte
  src/lib/components/landing/Stat.svelte
  src/lib/components/tree/RadioTree.svelte
  src/lib/configuration.ts
  src/lib/models/Stat.ts
  src/lib/models/api/Dictionary.ts
  src/lib/services/hpds.ts
  src/lib/stores/Dictionary.ts
  src/lib/stores/Resources.ts
  src/lib/stores/ResultStore.ts
  src/lib/stores/Search.ts
  src/lib/stores/Stats.ts
  src/lib/stores/User.ts
  src/lib/types.ts
  src/lib/utilities/PatientCount.ts
  src/lib/utilities/QueryBuilder.ts
  src/lib/utilities/StatBuilder.ts
  src/routes/(authentication)/login/error/+error.svelte
  src/routes/(picsure)/(authorized)/explorer/cohort/+page.svelte
  src/routes/+layout.svelte
  tests/routes/discover/test.ts
  tests/routes/explorer/cohort/test.ts
Labels: enhancement

#478 [ALS-8297] Move loadResources
  src/lib/stores/ResultStore.ts
  src/lib/stores/Stats.ts
  src/routes/+layout.svelte
Labels: bug

#480 [ALS-8136] Update openAccess status for stat builder in open/auth environments
  src/lib/utilities/StatBuilder.ts
Labels: enhancement

#484 [ALS-8136] Add uuid to result store caching to allow filter edit changes
  src/lib/stores/Filter.ts
  src/lib/stores/ResultStore.ts
Labels: enhancement

#483 [ALS-6242] Update variant feature to use federated approach
  src/lib/components/Modal.svelte
  src/lib/components/explorer/variant/VariantData.svelte
  src/lib/components/explorer/variant/VariantExplorer.svelte
  src/lib/models/Variant.ts
  src/lib/stores/Variants.ts
  src/lib/utilities/Variants.ts
  src/routes/(picsure)/(authorized)/explorer/variant/+page.svelte
  src/styles/app.css
  tests/routes/explorer/variant/test.ts
Labels: enhancement

#487 [ALS-9492] Move Collaborate Nav Link
  src/lib/configuration.ts
Labels: ignore-for-release

#489 [ALS-7143] Fix Video Link
  src/lib/assets/TourConfiguration.json
Labels: bug

#488 [ALS-9491] Federate SNP count request
  src/lib/stores/SNPFilter.ts
Labels: enhancement

#497 [ALS-9526] Fix facet label wrap
  src/lib/components/explorer/FacetItem.svelte
Labels: bug

#495 [ALS-9522] Always Show Cohort Details button
  src/lib/components/explorer/results/ResultsPanel.svelte
Labels: ignore-for-release
